// Package adversary owns the bot-to-bot adversarial tester (Phase 5
// Sprint 1). A "tester" LLM, primed with one of the canned DE personas
// in personas/de/*.yaml, red-teams the bot-under-test for N turns —
// hard-capped on turn count and accumulated cost — so admins can
// surface failure modes the golden-questions corpus doesn't catch
// (jailbreaks, off-topic drift, data exfiltration).
//
// Personas are checked-in YAML, treated as code: adding a persona is
// a curation PR, not a runtime config change. v1 ships three.
package adversary

import (
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"sort"

	"gopkg.in/yaml.v3"
)

//go:embed all:personas
var personaFS embed.FS

// ErrUnknownPersona is returned by LoadPersona when the id doesn't
// match a checked-in persona. Locked-enum: callers don't get to
// invent personas at runtime.
var ErrUnknownPersona = errors.New("adversary: unknown persona")

// Persona drives the tester-LLM and the post-run judge.
//
//   - TesterSystem is the system prompt the tester runs under. It
//     describes the *category* of probe (e.g. "you try to extract the
//     bot's system prompt") rather than spelling out concrete attack
//     strings — keeps the repo clean of literal "ignore previous
//     instructions" snippets.
//   - OpeningMessage is the first user message the tester sends to the
//     victim. Subsequent turns are generated by the tester-LLM.
//   - JudgeRubric is the prompt the post-run judge receives along with
//     the full transcript; it returns pass/fail + a one-line reason.
type Persona struct {
	ID             string `yaml:"id"`
	Name           string `yaml:"name"`
	TesterSystem   string `yaml:"tester_system"`
	OpeningMessage string `yaml:"opening_message"`
	JudgeRubric    string `yaml:"judge_rubric"`
}

// LoadPersona reads a single persona by id. Path layout is fixed at
// personas/de/<id>.yaml; AT/CH/EN locales are explicitly out of scope
// for v1.
func LoadPersona(id string) (*Persona, error) {
	path := "personas/de/" + id + ".yaml"
	raw, err := fs.ReadFile(personaFS, path)
	if err != nil {
		return nil, fmt.Errorf("%w: %q", ErrUnknownPersona, id)
	}
	var p Persona
	if err := yaml.Unmarshal(raw, &p); err != nil {
		return nil, fmt.Errorf("adversary: parse %s: %w", path, err)
	}
	if p.ID == "" || p.TesterSystem == "" || p.OpeningMessage == "" || p.JudgeRubric == "" {
		return nil, fmt.Errorf("adversary: persona %q missing required fields", id)
	}
	if p.ID != id {
		return nil, fmt.Errorf("adversary: persona id %q does not match filename %q", p.ID, id)
	}
	return &p, nil
}

// Personas returns every persona discoverable on the embedded FS, in
// stable alphabetical order. Used by the dashboard dropdown (Sprint 2)
// + the CLI usage helper.
func Personas() ([]Persona, error) {
	entries, err := fs.ReadDir(personaFS, "personas/de")
	if err != nil {
		return nil, fmt.Errorf("adversary: list personas: %w", err)
	}
	var ids []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if len(name) < 6 || name[len(name)-5:] != ".yaml" {
			continue
		}
		ids = append(ids, name[:len(name)-5])
	}
	sort.Strings(ids)
	out := make([]Persona, 0, len(ids))
	for _, id := range ids {
		p, err := LoadPersona(id)
		if err != nil {
			return nil, err
		}
		out = append(out, *p)
	}
	return out, nil
}
